const levels = [
	// Level 1 – easy start
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 75,
				y: 700,
				width: 100,
				height: 10,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 150,
				y: 650,
				width: 100,
				height: 10,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 300,
				y: 560,
				width: 100,
				height: 10,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 450,
				y: 470,
				width: 100,
				height: 10,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 600,
				y: 380,
				width: 100,
				height: 10,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 170, y: 620, width: 20, height: 20, collected: false },
			{ x: 470, y: 420, width: 20, height: 20, collected: false },
			{ x: 620, y: 320, width: 20, height: 20, collected: false },
		],
		buttons: [],
		powerUps: [],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 720, y: 310, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	// Level 2 – lots of small platforms
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 100,
				y: 700,
				width: 80,
				height: 10,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 200,
				y: 620,
				width: 80,
				height: 10,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 300,
				y: 540,
				width: 80,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 400,
				y: 460,
				width: 80,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 500,
				y: 380,
				width: 80,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 120, y: 670, width: 20, height: 20, collected: false },
			{ x: 320, y: 510, width: 20, height: 20, collected: false },
			{ x: 520, y: 350, width: 20, height: 20, collected: false },
		],
		buttons: [],
		powerUps: [],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 600, y: 340, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	// Level 3 - cross and cross
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			}, // dicker Boden
			{
				x: 100,
				y: 700,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 600,
				y: 700,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 250,
				y: 630,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 450,
				y: 630,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 125,
				y: 550,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 300,
				y: 460,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 200,
				y: 370,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 390,
				y: 280,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 200,
				y: 190,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 390,
				y: 100,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
		],

		movPlatforms: [],
		coins: [
			{ x: 50, y: 680, width: 20, height: 20, collected: false },
			{ x: 400, y: 610, width: 20, height: 20, collected: false },
			{ x: 350, y: 350, width: 20, height: 20, collected: false },
			{ x: 450, y: 260, width: 20, height: 20, collected: false },
		],
		buttons: [],
		powerUps: [],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 380, y: 20, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	// Level 4 – including one bonus coin
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 100,
				y: 700,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 250,
				y: 700,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 400,
				y: 610,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 520,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 200,
				y: 400,
				width: 100,
				height: 10,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "pink",
			}, // Bonusplattform
		],
		movPlatforms: [],
		coins: [
			{ x: 130, y: 670, width: 20, height: 20, collected: false },
			{ x: 420, y: 570, width: 20, height: 20, collected: false },
			{ x: 220, y: 370, width: 20, height: 20, collected: false }, // schwer erreichbar
		],
		buttons: [],
		powerUps: [],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 600, y: 460, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	//Level 5 - hidden platforms - you need to activate buttons to reveal them
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 100,
				y: 700,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 250,
				y: 700,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 400,
				y: 610,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 520,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},

			{
				x: 360,
				y: 480,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 250,
				y: 390,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 400,
				y: 300,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 210,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 120,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 300,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 130, y: 670, width: 20, height: 20, collected: false },
			{ x: 420, y: 570, width: 20, height: 20, collected: false },
			{ x: 220, y: 370, width: 20, height: 20, collected: false },
		],
		buttons: [
			{
				x: 700,
				y: 750,
				width: 40,
				height: 10,
				targetGroup: "A",
				pressed: false,
			},
		],
		powerUps: [],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 380, y: 10, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	//Level 6 - higher jump strength with power-up
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 150,
				y: 700,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 400,
				y: 610,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 520,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 730,
				y: 440,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 730,
				y: 250,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 500,
				y: 100,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 340, y: 670, width: 20, height: 20, collected: false },
			{ x: 550, y: 40, width: 20, height: 20, collected: false },
			{ x: 750, y: 200, width: 20, height: 20, collected: false },
		],
		buttons: [
			{
				x: 700,
				y: 750,
				width: 40,
				height: 10,
				targetGroup: "A",
				pressed: false,
			},
		],
		powerUps: [
			{
				x: 750,
				y: 400,
				width: 20,
				height: 20,
				type: "highJump",
				collected: false,
			},
		],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 380, y: 10, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	//Level 7 - floating effect
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 560,
				y: 700,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 430,
				y: 610,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 520,
				width: 120,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 730,
				y: 440,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 730,
				y: 250,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 640,
				y: 150,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 60,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 400,
				y: 60,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 340, y: 670, width: 20, height: 20, collected: false },
			{ x: 550, y: 40, width: 20, height: 20, collected: false },
			{ x: 750, y: 200, width: 20, height: 20, collected: false },
		],
		buttons: [],
		powerUps: [
			{
				x: 750,
				y: 400,
				width: 20,
				height: 20,
				type: "feather",
				collected: false,
			},
		],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 380, y: 10, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	//Level 8 - magnet
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 300,
				y: 670,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 200,
				y: 580,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 300,
				y: 490,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 200,
				y: 400,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 400,
				y: 320,
				width: 390,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 400, y: 40, width: 20, height: 20, collected: false },
			{ x: 430, y: 40, width: 20, height: 20, collected: false },
			{ x: 460, y: 40, width: 20, height: 20, collected: false },
			{ x: 490, y: 40, width: 20, height: 20, collected: false },
			{ x: 520, y: 40, width: 20, height: 20, collected: false },
			{ x: 550, y: 40, width: 20, height: 20, collected: false },
			{ x: 580, y: 40, width: 20, height: 20, collected: false },
			{ x: 610, y: 40, width: 20, height: 20, collected: false },
			{ x: 640, y: 40, width: 20, height: 20, collected: false },
			{ x: 670, y: 40, width: 20, height: 20, collected: false },
			{ x: 700, y: 40, width: 20, height: 20, collected: false },
			{ x: 730, y: 40, width: 20, height: 20, collected: false },
			{ x: 760, y: 40, width: 20, height: 20, collected: false },
		],
		buttons: [],
		powerUps: [
			{
				x: 750,
				y: 400,
				width: 20,
				height: 20,
				type: "magnet",
				collected: false,
			},
		],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 750, y: 720, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	//Level 9 - ground full of spikes with lots of coins and plattfroms
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 10,
				y: 720,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 10,
				y: 630,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 10,
				y: 540,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 10,
				y: 450,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 10,
				y: 360,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 10,
				y: 270,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 10,
				y: 180,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 10,
				y: 90,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 210,
				y: 100,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 210,
				y: 190,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 210,
				y: 280,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 210,
				y: 370,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 210,
				y: 460,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 210,
				y: 550,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 210,
				y: 640,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 210,
				y: 730,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 410,
				y: 720,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 410,
				y: 630,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "C",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 410,
				y: 540,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "C",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 410,
				y: 450,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "C",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 410,
				y: 360,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "C",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 410,
				y: 270,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "C",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 410,
				y: 180,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "C",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 410,
				y: 90,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "C",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 610,
				y: 100,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "C",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 610,
				y: 190,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "D",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 610,
				y: 280,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "D",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 610,
				y: 370,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "D",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 610,
				y: 460,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "D",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 610,
				y: 550,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "D",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 610,
				y: 640,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "D",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 610,
				y: 730,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "D",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 750,
				y: 400,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "E",
				color: "rgb(187, 131, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 0, y: 40, width: 20, height: 20, collected: false },
			{ x: 30, y: 40, width: 20, height: 20, collected: false },
			{ x: 60, y: 40, width: 20, height: 20, collected: false },
			{ x: 90, y: 40, width: 20, height: 20, collected: false },
			{ x: 120, y: 40, width: 20, height: 20, collected: false },
			{ x: 150, y: 40, width: 20, height: 20, collected: false },
			{ x: 180, y: 40, width: 20, height: 20, collected: false },
			{ x: 210, y: 40, width: 20, height: 20, collected: false },
			{ x: 240, y: 40, width: 20, height: 20, collected: false },
			{ x: 270, y: 40, width: 20, height: 20, collected: false },
			{ x: 300, y: 40, width: 20, height: 20, collected: false },
			{ x: 330, y: 40, width: 20, height: 20, collected: false },
			{ x: 360, y: 40, width: 20, height: 20, collected: false },
			{ x: 400, y: 40, width: 20, height: 20, collected: false },
			{ x: 430, y: 40, width: 20, height: 20, collected: false },
			{ x: 460, y: 40, width: 20, height: 20, collected: false },
			{ x: 490, y: 40, width: 20, height: 20, collected: false },
			{ x: 520, y: 40, width: 20, height: 20, collected: false },
			{ x: 550, y: 40, width: 20, height: 20, collected: false },
			{ x: 580, y: 40, width: 20, height: 20, collected: false },
			{ x: 610, y: 40, width: 20, height: 20, collected: false },
			{ x: 640, y: 40, width: 20, height: 20, collected: false },
			{ x: 670, y: 40, width: 20, height: 20, collected: false },
			{ x: 700, y: 40, width: 20, height: 20, collected: false },
			{ x: 730, y: 40, width: 20, height: 20, collected: false },
			{ x: 760, y: 40, width: 20, height: 20, collected: false },
			{ x: 10, y: 680, width: 20, height: 10, collected: false },
			{ x: 10, y: 610, width: 20, height: 10, collected: false },
			{ x: 10, y: 520, width: 20, height: 10, collected: false },
			{ x: 10, y: 430, width: 20, height: 10, collected: false },
			{ x: 10, y: 340, width: 20, height: 10, collected: false },
			{ x: 10, y: 250, width: 20, height: 10, collected: false },
			{ x: 10, y: 160, width: 20, height: 10, collected: false },
			{ x: 10, y: 70, width: 20, height: 10, collected: false },
			{ x: 210, y: 80, width: 20, height: 10, collected: false },
			{ x: 210, y: 170, width: 20, height: 10, collected: false },
			{ x: 210, y: 260, width: 20, height: 10, collected: false },
			{ x: 210, y: 350, width: 20, height: 10, collected: false },
			{ x: 210, y: 440, width: 20, height: 10, collected: false },
			{ x: 210, y: 530, width: 20, height: 10, collected: false },
			{ x: 210, y: 620, width: 20, height: 10, collected: false },
			{ x: 210, y: 710, width: 20, height: 10, collected: false },
			{ x: 410, y: 700, width: 20, height: 10, collected: false },
			{ x: 410, y: 610, width: 20, height: 10, collected: false },
			{ x: 410, y: 520, width: 20, height: 10, collected: false },
			{ x: 410, y: 430, width: 20, height: 10, collected: false },
			{ x: 410, y: 340, width: 20, height: 10, collected: false },
			{ x: 410, y: 250, width: 20, height: 10, collected: false },
			{ x: 410, y: 160, width: 20, height: 10, collected: false },
			{ x: 410, y: 70, width: 20, height: 10, collected: false },
			{ x: 610, y: 80, width: 20, height: 10, collected: false },
			{ x: 610, y: 170, width: 20, height: 10, collected: false },
			{ x: 610, y: 260, width: 20, height: 10, collected: false },
			{ x: 610, y: 350, width: 20, height: 10, collected: false },
			{ x: 610, y: 440, width: 20, height: 10, collected: false },
			{ x: 610, y: 530, width: 20, height: 10, collected: false },
			{ x: 610, y: 620, width: 20, height: 10, collected: false },
			{ x: 610, y: 710, width: 20, height: 10, collected: false },
			{ x: 750, y: 380, width: 20, height: 10, collected: false },
		],
		buttons: [
			{
				x: 10,
				y: 710,
				width: 40,
				height: 10,
				targetGroup: "A",
				pressed: false,
			},
			{
				x: 210,
				y: 90,
				width: 40,
				height: 10,
				targetGroup: "B",
				pressed: false,
			},
			{
				x: 410,
				y: 710,
				width: 40,
				height: 10,
				targetGroup: "C",
				pressed: false,
			},
			{
				x: 610,
				y: 90,
				width: 40,
				height: 10,
				targetGroup: "D",
				pressed: false,
			},
			{
				x: 610,
				y: 720,
				width: 40,
				height: 10,
				targetGroup: "E",
				pressed: false,
			},
		],
		powerUps: [],
		spikes: [
			{ x: 0, y: 740, width: 40, height: 20 },
			{ x: 40, y: 740, width: 40, height: 20 },
			{ x: 80, y: 740, width: 40, height: 20 },
			{ x: 120, y: 740, width: 40, height: 20 },
			{ x: 160, y: 740, width: 40, height: 20 },
			{ x: 200, y: 740, width: 40, height: 20 },
			{ x: 240, y: 740, width: 40, height: 20 },
			{ x: 280, y: 740, width: 40, height: 20 },
			{ x: 320, y: 740, width: 40, height: 20 },
			{ x: 360, y: 740, width: 40, height: 20 },
			{ x: 400, y: 740, width: 40, height: 20 },
			{ x: 440, y: 740, width: 40, height: 20 },
			{ x: 480, y: 740, width: 40, height: 20 },
			{ x: 520, y: 740, width: 40, height: 20 },
			{ x: 560, y: 740, width: 40, height: 20 },
			{ x: 600, y: 740, width: 40, height: 20 },
			{ x: 640, y: 740, width: 40, height: 20 },
			{ x: 680, y: 740, width: 40, height: 20 },
			{ x: 720, y: 740, width: 40, height: 20 },
			{ x: 760, y: 740, width: 40, height: 20 },
		],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 750, y: 360, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	// Level 10 – higher jumping strength due to power-up
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 100,
				y: 690,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 250,
				y: 630,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 400,
				y: 570,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 510,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 650,
				y: 440,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 500,
				y: 380,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 350,
				y: 320,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 200,
				y: 260,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 50,
				y: 200,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 600,
				y: 300,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 700,
				y: 240,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 600,
				y: 180,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 50,
				y: 120,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(85, 60, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 110, y: 660, width: 20, height: 20, collected: false },
			{ x: 260, y: 600, width: 20, height: 20, collected: false },
			{ x: 410, y: 540, width: 20, height: 20, collected: false },
			{ x: 560, y: 480, width: 20, height: 20, collected: false },
			{ x: 660, y: 410, width: 20, height: 20, collected: false },
			{ x: 510, y: 350, width: 20, height: 20, collected: false },
			{ x: 360, y: 290, width: 20, height: 20, collected: false },
			{ x: 210, y: 230, width: 20, height: 20, collected: false },
			{ x: 60, y: 170, width: 20, height: 20, collected: false },
			{ x: 210, y: 110, width: 20, height: 20, collected: false },
			{ x: 390, y: 50, width: 20, height: 20, collected: false },
			{ x: 460, y: 90, width: 20, height: 20, collected: false },
			{ x: 610, y: 150, width: 20, height: 20, collected: false },
			{ x: 710, y: 210, width: 20, height: 20, collected: false },
			{ x: 610, y: 270, width: 20, height: 20, collected: false },
		],
		buttons: [
			{
				x: 210,
				y: 250,
				width: 40,
				height: 10,
				targetGroup: "B",
				pressed: false,
			},
		],
		powerUps: [
			{
				x: 720,
				y: 420,
				width: 20,
				height: 20,
				type: "highJump",
				collected: false,
			},
		],
		spikes: [
			{ x: 0, y: 740, width: 40, height: 20 },
			{ x: 40, y: 740, width: 40, height: 20 },
			{ x: 80, y: 740, width: 40, height: 20 },
			{ x: 120, y: 740, width: 40, height: 20 },
			{ x: 160, y: 740, width: 40, height: 20 },
			{ x: 200, y: 740, width: 40, height: 20 },
			{ x: 240, y: 740, width: 40, height: 20 },
			{ x: 280, y: 740, width: 40, height: 20 },
			{ x: 320, y: 740, width: 40, height: 20 },
			{ x: 360, y: 740, width: 40, height: 20 },
			{ x: 400, y: 740, width: 40, height: 20 },
			{ x: 440, y: 740, width: 40, height: 20 },
			{ x: 480, y: 740, width: 40, height: 20 },
			{ x: 520, y: 740, width: 40, height: 20 },
			{ x: 560, y: 740, width: 40, height: 20 },
			{ x: 600, y: 740, width: 40, height: 20 },
			{ x: 640, y: 740, width: 40, height: 20 },
			{ x: 680, y: 740, width: 40, height: 20 },
			{ x: 720, y: 740, width: 40, height: 20 },
			{ x: 760, y: 740, width: 40, height: 20 },
		],
		portals: [],
		platRespawnTime: 3500,
		goal: { x: 380, y: 20, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	// Level 11 – Hidden platforms - you can't even activate them by a button
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 100,
				y: 670,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 250,
				y: 580,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 400,
				y: 500,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 550,
				y: 420,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "transparent",
			},
			{
				x: 400,
				y: 340,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 250,
				y: 260,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "transparent",
			},
			{
				x: 100,
				y: 180,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 250,
				y: 100,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "transparent",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 120, y: 630, width: 20, height: 20, collected: false },
			{ x: 270, y: 550, width: 20, height: 20, collected: false },
			{ x: 420, y: 470, width: 20, height: 20, collected: false },
			{ x: 440, y: 310, width: 20, height: 20, collected: false },
			{ x: 290, y: 230, width: 20, height: 20, collected: false },
			{ x: 150, y: 150, width: 20, height: 20, collected: false },
			{ x: 270, y: 70, width: 20, height: 20, collected: false },
			{ x: 550, y: 400, width: 20, height: 20, collected: false },
		],
		buttons: [],
		powerUps: [],
		spikes: [
			{ x: 110, y: 160, width: 40, height: 20 },
			{ x: 400, y: 320, width: 40, height: 20 },
		],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 380, y: 20, width: 40, height: 40 },
		width: 800,
		height: 800,
	},

	// Level 12 - moving platforms
	{
		platforms: [
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				group: "A",
				color: "green",
			}, // Boden

			// Normale Plattformen mit Münzen
			{
				x: 100,
				y: 680,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 200,
				y: 600,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 300,
				y: 520,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 400,
				y: 440,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 500,
				y: 360,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 600,
				y: 280,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 100,
				y: 200,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 200,
				y: 120,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 300,
				y: 80,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: true,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "B",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 600,
				y: 730,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 750,
				y: 100,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			}, // unter Goal
		],
		movPlatforms: [
			// Moving platforms
			{
				x: 100,
				y: 280,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				type: "horizontalMoving",
				originalX: 100,
				originalY: 350,
				range: 200,
				speed: 1.5,
				movingForward: true,
				movingDownwards: false,
				active: true,
				color: "blue",
				group: "A",
			},

			// Moving platform that can be activated by a button
			{
				x: 650,
				y: 670,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				type: "verticalMoving",
				originalX: 650,
				originalY: 670,
				range: 500,
				speed: 1.5,
				movingForward: false,
				movingDownwards: false,
				active: false,
				color: "purple",
				group: "B",
			},
		],

		coins: [
			{ x: 110, y: 660, width: 20, height: 20, collected: false },
			{ x: 210, y: 580, width: 20, height: 20, collected: false },
			{ x: 310, y: 500, width: 20, height: 20, collected: false },
			{ x: 410, y: 420, width: 20, height: 20, collected: false },
			{ x: 510, y: 340, width: 20, height: 20, collected: false },
			{ x: 610, y: 260, width: 20, height: 20, collected: false },
			{ x: 110, y: 180, width: 20, height: 20, collected: false },
			{ x: 210, y: 100, width: 20, height: 20, collected: false },
			{ x: 310, y: 60, width: 20, height: 20, collected: false },
			{ x: 390, y: 40, width: 20, height: 20, collected: false },
		],

		buttons: [
			{
				x: 600,
				y: 720,
				width: 40,
				height: 10,
				targetGroup: "B",
				pressed: false,
			},
		],

		powerUps: [],

		spikes: [
			{ x: 0, y: 740, width: 100, height: 20 },
			{ x: 700, y: 740, width: 100, height: 20 },
			{ x: 300, y: 740, width: 100, height: 20 },
		],

		portals: [],
		platRespawnTime: 2500,
		goal: { x: 750, y: 60, width: 40, height: 40 },
		width: 800,
		height: 800,
	},
	// Level 13 - just a simple level
	{
		platforms: [
			// Boden
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},

			// Startrampe
			{
				x: 50,
				y: 700,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},

			// Statische Zwischenplattformen
			{
				x: 250,
				y: 650,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			{
				x: 500,
				y: 590,
				width: 100,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},
			//Plattform unter Button
			{
				x: 710,
				y: 400,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},

			// Plattform unter dem Ziel
			{
				x: 700,
				y: 100,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
		],

		movPlatforms: [
			// Vertikale Plattform, durch Button aktiviert
			{
				x: 600,
				y: 730,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				type: "verticalMoving",
				originalX: 600,
				originalY: 730,
				range: 600,
				speed: 1.8,
				movingForward: false,
				movingDownwards: false,
				active: false,
				color: "purple",
				group: "B",
			},
		],

		coins: [
			{ x: 60, y: 680, width: 20, height: 20, collected: false },
			{ x: 260, y: 630, width: 20, height: 20, collected: false },
			{ x: 510, y: 570, width: 20, height: 20, collected: false },
			{ x: 160, y: 480, width: 20, height: 20, collected: false },
			{ x: 310, y: 430, width: 20, height: 20, collected: false },
			{ x: 410, y: 350, width: 20, height: 20, collected: false },
		],

		buttons: [
			{
				x: 710,
				y: 390,
				width: 40,
				height: 10,
				targetGroup: "B",
				pressed: false,
			},
		],

		powerUps: [
			{
				x: 500,
				y: 540,
				width: 20,
				height: 20,
				collected: false,
				type: "highJump",
			},
		],

		spikes: [
			{ x: 400, y: 740, width: 100, height: 20 },
			{ x: 200, y: 740, width: 80, height: 20 },
		],

		portals: [],
		platRespawnTime: 2500,
		goal: { x: 700, y: 60, width: 40, height: 40 },
		width: 800,
		height: 800,
	},
	// Level 14 - extra hard level due to a short-lasting power-up
	{
		platforms: [
			// Boden
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},

			// Startplattform
			{
				x: 50,
				y: 700,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},

			// Hohe Plattform vor Power-Up
			{
				x: 300,
				y: 600,
				width: 60,
				height: 10,
				solid: false,
				breakable: true,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 1500,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},

			// Plattform über Abgrund, nur mit "feather" erreichbar
			{
				x: 500,
				y: 450,
				width: 80,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(85, 60, 0)",
			},

			// Zielplattform
			{
				x: 710,
				y: 200,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
		],

		movPlatforms: [],

		coins: [
			{ x: 70, y: 680, width: 20, height: 20, collected: false },
			{ x: 710, y: 100, width: 20, height: 20, collected: false },
			{ x: 360, y: 510, width: 20, height: 20, collected: false },
			{ x: 520, y: 430, width: 20, height: 20, collected: false },
			{ x: 720, y: 180, width: 20, height: 20, collected: false },
		],

		buttons: [],

		powerUps: [
			{
				x: 310,
				y: 570,
				width: 20,
				height: 20,
				collected: false,
				type: "feather",
			},
		],

		spikes: [
			{ x: 200, y: 740, width: 100, height: 20 },
			{ x: 400, y: 740, width: 100, height: 20 },
			{ x: 600, y: 740, width: 100, height: 20 },
		],

		portals: [],
		platRespawnTime: 2500,
		goal: { x: 710, y: 160, width: 40, height: 40 },
		width: 800,
		height: 800,
	},
	// Level 15 - Level divided into to parts
	{
		platforms: [
			// Boden
			{
				x: 0,
				y: 760,
				width: 800,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},

			// Zwischenboden
			{
				x: 0,
				y: 325,
				width: 800,
				height: 25,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "black",
			},

			//Plattformen erste Ebene
			{
				x: 530,
				y: 250,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 530,
				y: 155,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				// Plattform unter 1. Portal
				x: 710,
				y: 180,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},

			// Plattformen zweite Ebene
			{
				// Plattform unter 2. Portal
				x: 710,
				y: 701,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 660,
				y: 630,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 560,
				y: 560,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 510,
				y: 470,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 350,
				y: 535,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 200,
				y: 620,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 50,
				y: 705,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 50,
				y: 610,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 50,
				y: 515,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
		],

		movPlatforms: [],

		coins: [
			{ x: 60, y: 680, width: 20, height: 20, collected: false },
			{ x: 710, y: 100, width: 20, height: 20, collected: false },
			{ x: 360, y: 510, width: 20, height: 20, collected: false },
			{ x: 520, y: 445, width: 20, height: 20, collected: false },
		],

		buttons: [],

		powerUps: [],

		spikes: [
			{ x: 0, y: 740, width: 40, height: 20 },
			{ x: 40, y: 740, width: 40, height: 20 },
			{ x: 80, y: 740, width: 40, height: 20 },
			{ x: 120, y: 740, width: 40, height: 20 },
			{ x: 160, y: 740, width: 40, height: 20 },
			{ x: 200, y: 740, width: 40, height: 20 },
			{ x: 240, y: 740, width: 40, height: 20 },
			{ x: 280, y: 740, width: 40, height: 20 },
			{ x: 320, y: 740, width: 40, height: 20 },
			{ x: 360, y: 740, width: 40, height: 20 },
			{ x: 400, y: 740, width: 40, height: 20 },
			{ x: 440, y: 740, width: 40, height: 20 },
			{ x: 480, y: 740, width: 40, height: 20 },
			{ x: 520, y: 740, width: 40, height: 20 },
			{ x: 560, y: 740, width: 40, height: 20 },
			{ x: 600, y: 740, width: 40, height: 20 },
			{ x: 640, y: 740, width: 40, height: 20 },
			{ x: 680, y: 740, width: 40, height: 20 },
			{ x: 720, y: 740, width: 40, height: 20 },
			{ x: 760, y: 740, width: 40, height: 20 },
		],

		portals: [
			{
				x: 710,
				y: 140,
				width: 40,
				height: 40,
				color: "cyan",
				type: "start",
				group: "A",
			},
			{
				x: 710,
				y: 660,
				width: 40,
				height: 40,
				color: "cyan",
				type: "end",
				group: "A",
			},
		],
		platRespawnTime: 2500,
		goal: { x: 50, y: 420, width: 40, height: 40 },
		width: 800,
		height: 800,
	},
	// Level 16 - bigger level
	{
		platforms: [
			// Boden
			{
				x: 0,
				y: 910,
				width: 1000,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			{
				x: 50,
				y: 250,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 100,
				y: 180,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 120,
				y: 280,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 200,
				y: 140,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 450,
				y: 50,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 450,
				y: 150,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 320,
				y: 100,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 265,
				y: 230,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 550,
				y: 165,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 660,
				y: 250,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 710,
				y: 180,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 735,
				y: 250,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 830,
				y: 160,
				width: 40,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
		],

		movPlatforms: [],

		coins: [
			{ x: 120, y: 875, width: 20, height: 20, collected: false },
			{ x: 160, y: 875, width: 20, height: 20, collected: false },
			{ x: 200, y: 875, width: 20, height: 20, collected: false },
			{ x: 240, y: 875, width: 20, height: 20, collected: false },
			{ x: 280, y: 875, width: 20, height: 20, collected: false },
			{ x: 320, y: 875, width: 20, height: 20, collected: false },
			{ x: 360, y: 875, width: 20, height: 20, collected: false },
			{ x: 400, y: 875, width: 20, height: 20, collected: false },
			{ x: 440, y: 875, width: 20, height: 20, collected: false },
			{ x: 480, y: 875, width: 20, height: 20, collected: false },
			{ x: 520, y: 875, width: 20, height: 20, collected: false },
			{ x: 560, y: 875, width: 20, height: 20, collected: false },
			{ x: 600, y: 875, width: 20, height: 20, collected: false },
			{ x: 640, y: 875, width: 20, height: 20, collected: false },
			{ x: 680, y: 875, width: 20, height: 20, collected: false },
			{ x: 720, y: 875, width: 20, height: 20, collected: false },
			{ x: 760, y: 875, width: 20, height: 20, collected: false },
		],

		buttons: [],

		powerUps: [],

		spikes: [
			{ x: 0, y: 300, width: 40, height: 20 },
			{ x: 40, y: 300, width: 40, height: 20 },
			{ x: 80, y: 300, width: 40, height: 20 },
			{ x: 120, y: 300, width: 40, height: 20 },
			{ x: 160, y: 300, width: 40, height: 20 },
			{ x: 200, y: 300, width: 40, height: 20 },
			{ x: 240, y: 300, width: 40, height: 20 },
			{ x: 280, y: 300, width: 40, height: 20 },
			{ x: 320, y: 300, width: 40, height: 20 },
			{ x: 360, y: 300, width: 40, height: 20 },
			{ x: 400, y: 300, width: 40, height: 20 },
			{ x: 440, y: 300, width: 40, height: 20 },
			{ x: 480, y: 300, width: 40, height: 20 },
			{ x: 520, y: 300, width: 40, height: 20 },
			{ x: 560, y: 300, width: 40, height: 20 },
			{ x: 600, y: 300, width: 40, height: 20 },
			{ x: 640, y: 300, width: 40, height: 20 },
			{ x: 680, y: 300, width: 40, height: 20 },
			{ x: 720, y: 300, width: 40, height: 20 },
			{ x: 760, y: 300, width: 40, height: 20 },
			{ x: 800, y: 300, width: 40, height: 20 },
			{ x: 840, y: 300, width: 40, height: 20 },
			{ x: 880, y: 300, width: 40, height: 20 },
			{ x: 920, y: 300, width: 40, height: 20 },
			{ x: 960, y: 300, width: 40, height: 20 },
			{ x: 0, y: 500, width: 40, height: 20 },
			{ x: 40, y: 500, width: 40, height: 20 },
			{ x: 80, y: 500, width: 40, height: 20 },
			{ x: 120, y: 500, width: 40, height: 20 },
			{ x: 160, y: 500, width: 40, height: 20 },
			{ x: 200, y: 500, width: 40, height: 20 },
			{ x: 240, y: 500, width: 40, height: 20 },
			{ x: 280, y: 500, width: 40, height: 20 },
			{ x: 320, y: 500, width: 40, height: 20 },
			{ x: 360, y: 500, width: 40, height: 20 },
			{ x: 400, y: 500, width: 40, height: 20 },
			{ x: 440, y: 500, width: 40, height: 20 },
			{ x: 480, y: 500, width: 40, height: 20 },
			{ x: 520, y: 500, width: 40, height: 20 },
			{ x: 560, y: 500, width: 40, height: 20 },
			{ x: 600, y: 500, width: 40, height: 20 },
			{ x: 640, y: 500, width: 40, height: 20 },
			{ x: 680, y: 500, width: 40, height: 20 },
			{ x: 720, y: 500, width: 40, height: 20 },
			{ x: 760, y: 500, width: 40, height: 20 },
			{ x: 800, y: 500, width: 40, height: 20 },
			{ x: 840, y: 500, width: 40, height: 20 },
			{ x: 880, y: 500, width: 40, height: 20 },
			{ x: 920, y: 500, width: 40, height: 20 },
			{ x: 960, y: 500, width: 40, height: 20 },
			{ x: 0, y: 740, width: 40, height: 20 },
			{ x: 40, y: 740, width: 40, height: 20 },
			{ x: 80, y: 740, width: 40, height: 20 },
			{ x: 120, y: 740, width: 40, height: 20 },
			{ x: 160, y: 740, width: 40, height: 20 },
			{ x: 200, y: 740, width: 40, height: 20 },
			{ x: 240, y: 740, width: 40, height: 20 },
			{ x: 280, y: 740, width: 40, height: 20 },
			{ x: 320, y: 740, width: 40, height: 20 },
			{ x: 360, y: 740, width: 40, height: 20 },
			{ x: 400, y: 740, width: 40, height: 20 },
			{ x: 440, y: 740, width: 40, height: 20 },
			{ x: 480, y: 740, width: 40, height: 20 },
			{ x: 520, y: 740, width: 40, height: 20 },
			{ x: 560, y: 740, width: 40, height: 20 },
			{ x: 600, y: 740, width: 40, height: 20 },
			{ x: 640, y: 740, width: 40, height: 20 },
			{ x: 680, y: 740, width: 40, height: 20 },
			{ x: 720, y: 740, width: 40, height: 20 },
			{ x: 760, y: 740, width: 40, height: 20 },
			{ x: 800, y: 740, width: 40, height: 20 },
			{ x: 840, y: 740, width: 40, height: 20 },
			{ x: 880, y: 740, width: 40, height: 20 },
			{ x: 920, y: 740, width: 40, height: 20 },
			{ x: 960, y: 740, width: 40, height: 20 },
		],

		portals: [
			{
				x: 710,
				y: 140,
				width: 40,
				height: 40,
				color: "cyan",
				type: "start",
				group: "A",
			},
			{
				x: 50,
				y: 360,
				width: 40,
				height: 40,
				color: "cyan",
				type: "end",
				group: "A",
			},
			{
				x: 100,
				y: 140,
				width: 40,
				height: 40,
				color: "cyan",
				type: "start",
				group: "B",
			},
			{
				x: 850,
				y: 860,
				width: 40,
				height: 40,
				color: "cyan",
				type: "start",
				group: "B",
			},
			{
				x: 50,
				y: 660,
				width: 40,
				height: 40,
				color: "cyan",
				type: "end",
				group: "B",
			},
			{
				x: 950,
				y: 10,
				width: 40,
				height: 40,
				color: "cyan",
				type: "start",
				group: "C",
			},
			{
				x: 50,
				y: 860,
				width: 40,
				height: 40,
				color: "cyan",
				type: "end",
				group: "C",
			},
			{
				x: 910,
				y: 850,
				width: 40,
				height: 40,
				color: "cyan",
				type: "start",
				group: "D",
			},
			{
				x: 450,
				y: 10,
				width: 40,
				height: 40,
				color: "cyan",
				type: "end",
				group: "D",
			},
		],
		platRespawnTime: 2500,
		goal: { x: 90, y: 420, width: 40, height: 40 },
		width: 1000,
		height: 950,
	},
	// Level 17 - an almost impossible level as you can't see some platforms which are spreaded all over the level and which you have to jump with an extra jump on
	{
		// ground
		platforms: [
			{
				x: 0,
				y: 910,
				width: 1000,
				height: 40,
				solid: true,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "green",
			},
			// hidden platforms under the portal
			{
				x: 840,
				y: 510,
				width: 150,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "transparent",
			},
			{
				x: 840,
				y: 720,
				width: 150,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "transparent",
			},
			{
				x: 840,
				y: 300,
				width: 150,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "transparent",
			},
			// hidden platforms on the left side under the coins
			{
				x: 280,
				y: 510,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "transparent",
			},
			{
				x: 280,
				y: 720,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "transparent",
			},
			// beige platforms in the middle
			{
				x: 620,
				y: 510,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 620,
				y: 720,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
			{
				x: 620,
				y: 300,
				width: 100,
				height: 10,
				solid: false,
				breakable: false,
				isBroken: false,
				breakTimer: null,
				timeTillBreakAfterContact: 2000,
				respawnTimer: null,
				group: "A",
				color: "rgb(187, 131, 0)",
			},
		],
		movPlatforms: [],
		coins: [
			{ x: 120, y: 630, width: 20, height: 20, collected: false },
			{ x: 120, y: 550, width: 20, height: 20, collected: false },
			{ x: 120, y: 470, width: 20, height: 20, collected: false },
			{ x: 120, y: 310, width: 20, height: 20, collected: false },
			{ x: 120, y: 230, width: 20, height: 20, collected: false },
			{ x: 120, y: 150, width: 20, height: 20, collected: false },
			{ x: 120, y: 70, width: 20, height: 20, collected: false },
			{ x: 120, y: 400, width: 20, height: 20, collected: false },
			{ x: 320, y: 250, width: 20, height: 20, collected: false },
			{ x: 320, y: 390, width: 20, height: 20, collected: false },
			{ x: 320, y: 320, width: 20, height: 20, collected: false },
			{ x: 905, y: 480, width: 20, height: 20, collected: false },
			{ x: 905, y: 680, width: 20, height: 20, collected: false },
		],
		buttons: [],
		powerUps: [
			// high jump power-up
			{
				x: 320,
				y: 870,
				width: 20,
				height: 20,
				type: "highJump",
				collected: false,
			},
		],
		spikes: [],
		portals: [],
		platRespawnTime: 2500,
		goal: { x: 940, y: 40, width: 40, height: 40 },
		width: 1000,
		height: 950,
	},
];
// Export the levels array
export default levels;
